#!/bin/bash
# NEXTFLOW TASK: STAR_ALIGN (null)
set -e
set -u
NXF_DEBUG=${NXF_DEBUG:=0}; [[ $NXF_DEBUG > 1 ]] && set -x
NXF_ENTRY=${1:-nxf_main}


nxf_sleep() {
  sleep $1 2>/dev/null || sleep 1;
}

nxf_date() {
    local ts=$(date +%s%3N);
    if [[ ${#ts} == 10 ]]; then echo ${ts}000
    elif [[ $ts == *%3N ]]; then echo ${ts/\%3N/000}
    elif [[ $ts == *3N ]]; then echo ${ts/3N/000}
    elif [[ ${#ts} == 13 ]]; then echo $ts
    else echo "Unexpected timestamp value: $ts"; exit 1
    fi
}

nxf_env() {
    echo '============= task environment ============='
    env | sort | sed "s/\(.*\)AWS\(.*\)=\(.\{6\}\).*/\1AWS\2=\3xxxxxxxxxxxxx/"
    echo '============= task output =================='
}

nxf_kill() {
    declare -a children
    while read P PP;do
        children[$PP]+=" $P"
    done < <(ps -e -o pid= -o ppid=)

    kill_all() {
        [[ $1 != $$ ]] && kill $1 2>/dev/null || true
        for i in ${children[$1]:=}; do kill_all $i; done
    }

    kill_all $1
}

nxf_mktemp() {
    local base=${1:-/tmp}
    mkdir -p "$base"
    if [[ $(uname) = Darwin ]]; then mktemp -d $base/nxf.XXXXXXXXXX
    else TMPDIR="$base" mktemp -d -t nxf.XXXXXXXXXX
    fi
}

nxf_fs_copy() {
  local source=$1
  local target=$2
  local basedir=$(dirname $1)
  mkdir -p $target/$basedir
  cp -fRL $source $target/$basedir
}

nxf_fs_move() {
  local source=$1
  local target=$2
  local basedir=$(dirname $1)
  mkdir -p $target/$basedir
  mv -f $source $target/$basedir
}

nxf_fs_rsync() {
  rsync -rRl $1 $2
}

nxf_fs_rclone() {
  rclone copyto $1 $2/$1
}

nxf_fs_fcp() {
  fcp $1 $2/$1
}

on_exit() {
    exit_status=${nxf_main_ret:=$?}
    printf -- $exit_status > /Users/tw1628/Desktop/tracer-workflow-templates/work/48/3b2674965c2f7d8e00b7e3f042514a/.exitcode
    set +u
    exit $exit_status
}

on_term() {
    set +e
    [[ "$pid" ]] && nxf_kill $pid
}

nxf_launch() {
    /bin/bash -ue /Users/tw1628/Desktop/tracer-workflow-templates/work/48/3b2674965c2f7d8e00b7e3f042514a/.command.sh
}

nxf_stage() {
    true
    # stage input files
    rm -f human/Log.out
    rm -f human/sjdbInfo.txt
    rm -f human/exonGeTrInfo.tab
    rm -f human/transcriptInfo.tab
    rm -f human/genomeParameters.txt
    rm -f human/exonInfo.tab
    rm -f human/geneInfo.tab
    rm -f human/sjdbList.fromGTF.out.tab
    rm -f human/SAindex
    rm -f human/Genome
    rm -f human/SA
    rm -f human/chrLength.txt
    rm -f human/sjdbList.out.tab
    rm -f s1_1.fq
    rm -f human/chrName.txt
    rm -f s1_2.fq
    rm -f human/chrNameLength.txt
    rm -f human/chrStart.txt
    mkdir -p human && ln -s /Users/tw1628/Desktop/tracer-workflow-templates/work/8e/8a4921d4ef6a771925319a15b444dc/human/Log.out human/Log.out
    mkdir -p human && ln -s /Users/tw1628/Desktop/tracer-workflow-templates/work/8e/8a4921d4ef6a771925319a15b444dc/human/sjdbInfo.txt human/sjdbInfo.txt
    mkdir -p human && ln -s /Users/tw1628/Desktop/tracer-workflow-templates/work/8e/8a4921d4ef6a771925319a15b444dc/human/exonGeTrInfo.tab human/exonGeTrInfo.tab
    mkdir -p human && ln -s /Users/tw1628/Desktop/tracer-workflow-templates/work/8e/8a4921d4ef6a771925319a15b444dc/human/transcriptInfo.tab human/transcriptInfo.tab
    mkdir -p human && ln -s /Users/tw1628/Desktop/tracer-workflow-templates/work/8e/8a4921d4ef6a771925319a15b444dc/human/genomeParameters.txt human/genomeParameters.txt
    mkdir -p human && ln -s /Users/tw1628/Desktop/tracer-workflow-templates/work/8e/8a4921d4ef6a771925319a15b444dc/human/exonInfo.tab human/exonInfo.tab
    mkdir -p human && ln -s /Users/tw1628/Desktop/tracer-workflow-templates/work/8e/8a4921d4ef6a771925319a15b444dc/human/geneInfo.tab human/geneInfo.tab
    mkdir -p human && ln -s /Users/tw1628/Desktop/tracer-workflow-templates/work/8e/8a4921d4ef6a771925319a15b444dc/human/sjdbList.fromGTF.out.tab human/sjdbList.fromGTF.out.tab
    mkdir -p human && ln -s /Users/tw1628/Desktop/tracer-workflow-templates/work/8e/8a4921d4ef6a771925319a15b444dc/human/SAindex human/SAindex
    mkdir -p human && ln -s /Users/tw1628/Desktop/tracer-workflow-templates/work/8e/8a4921d4ef6a771925319a15b444dc/human/Genome human/Genome
    mkdir -p human && ln -s /Users/tw1628/Desktop/tracer-workflow-templates/work/8e/8a4921d4ef6a771925319a15b444dc/human/SA human/SA
    mkdir -p human && ln -s /Users/tw1628/Desktop/tracer-workflow-templates/work/8e/8a4921d4ef6a771925319a15b444dc/human/chrLength.txt human/chrLength.txt
    mkdir -p human && ln -s /Users/tw1628/Desktop/tracer-workflow-templates/work/8e/8a4921d4ef6a771925319a15b444dc/human/sjdbList.out.tab human/sjdbList.out.tab
    ln -s /Users/tw1628/Desktop/tracer-workflow-templates/data/s1_1.fq s1_1.fq
    mkdir -p human && ln -s /Users/tw1628/Desktop/tracer-workflow-templates/work/8e/8a4921d4ef6a771925319a15b444dc/human/chrName.txt human/chrName.txt
    ln -s /Users/tw1628/Desktop/tracer-workflow-templates/data/s1_2.fq s1_2.fq
    mkdir -p human && ln -s /Users/tw1628/Desktop/tracer-workflow-templates/work/8e/8a4921d4ef6a771925319a15b444dc/human/chrNameLength.txt human/chrNameLength.txt
    mkdir -p human && ln -s /Users/tw1628/Desktop/tracer-workflow-templates/work/8e/8a4921d4ef6a771925319a15b444dc/human/chrStart.txt human/chrStart.txt
}

nxf_unstage() {
    true
    [[ ${nxf_main_ret:=0} != 0 ]] && return
}

nxf_main() {
    trap on_exit EXIT
    trap on_term TERM INT USR2
    trap '' USR1

    [[ "${NXF_CHDIR:-}" ]] && cd "$NXF_CHDIR"
    NXF_SCRATCH=''
    [[ $NXF_DEBUG > 0 ]] && nxf_env
    touch /Users/tw1628/Desktop/tracer-workflow-templates/work/48/3b2674965c2f7d8e00b7e3f042514a/.command.begin
    set +u
    set -u
    [[ $NXF_SCRATCH ]] && cd $NXF_SCRATCH
    export NXF_TASK_WORKDIR="$PWD"
    nxf_stage

    set +e
    (set -o pipefail; (nxf_launch | tee .command.out) 3>&1 1>&2 2>&3 | tee .command.err) &
    pid=$!
    wait $pid || nxf_main_ret=$?
    nxf_unstage
}

$NXF_ENTRY
