FROM gitpod/workspace-base

USER root

# Install util tools.
# software-properties-common is needed to add ppa support for Apptainer installation
RUN apt-get update --quiet && \
    apt-get install --quiet --yes \
        apt-transport-https \
        apt-utils \
        sudo \
        git \
        less \
        wget \
        curl \
        tree \
        graphviz \
        software-properties-common

# Taken from: https://github.com/nf-core/tools/blob/master/nf_core/gitpod/gitpod.Dockerfile
# Install Apptainer (Singularity)
RUN add-apt-repository -y ppa:apptainer/ppa && \
    apt-get update --quiet && \
    apt install -y apptainer

# Install Conda
RUN wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh && \ 
    bash Miniconda3-latest-Linux-x86_64.sh -b -p /opt/conda && \
    rm Miniconda3-latest-Linux-x86_64.sh

ENV PATH="/opt/conda/bin:$PATH"

# Ensure conda can use the cache directories without permission issues
RUN mkdir -p /home/gitpod/.cache/conda && \
    chown -R gitpod:gitpod /home/gitpod/.cache /opt/conda /workspace

# Install R and required dependencies
RUN apt-get update --quiet && \
    apt-get install --quiet --yes \
        r-base \
        libxml2-dev \
        libcurl4-openssl-dev \
        libssl-dev \
        libfontconfig1-dev \
        libharfbuzz-dev \
        libfribidi-dev \
        libfreetype6-dev \
        libpng-dev \
        libtiff5-dev \
        libjpeg-dev \
        libgit2-dev \
        libglpk-dev \
        make \
        build-essential

# Create a writable library path for R packages
ENV R_LIBS_USER=/usr/local/lib/R/site-library

# Ensure the library path is writable
RUN mkdir -p $R_LIBS_USER && \
    chmod -R 777 $R_LIBS_USER

# Install R packages
RUN R -e "install.packages(c('BiocManager', 'ggplot2'), repos='http://cran.rstudio.com/')"

# Install Bioconductor packages
RUN R -e "BiocManager::install(c('DESeq2', 'tximport', 'apeglm', 'edgeR', 'limma', 'EnhancedVolcano'))"

# Change user to gitpod
USER gitpod

# Uncomment if we need to pin the Nextflow version
ENV NXF_EDGE=1
ENV NXF_VER=24.02.0-edge

# Install nextflow, nf-core, Mamba, and pytest-workflow
RUN conda config --add channels defaults && \
    conda config --add channels bioconda && \
    conda config --add channels conda-forge && \
    conda config --set channel_priority strict && \
    conda update --quiet --yes --all && \
    conda install --quiet --yes --name base \
        salmon \
        boost \
        star \
        macs3 \
        multiqc \
        subread \
        kallisto \
        hisat2 \
        bwa \
        bowtie2 \
        fastqc \
        gawk \
        samtools \
        mamba \
        nextflow \
        nf-core \
        nf-test \
        stringtie \
        black \
        prettier \
        pre-commit \
        pytest-workflow \
        snakemake && \
    conda clean --all --force-pkgs-dirs --yes

# Install deeptools
RUN python -m ensurepip --upgrade && pip install deeptools

# Update Nextflow
RUN nextflow self-update && nextflow -version

RUN unset JAVA_TOOL_OPTIONS

RUN export PS1='\t -> '

# Set the entrypoint to bash
ENTRYPOINT ["bash"]